### ISSUE TITLE
Improve threads polling

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#1076]
Improve/replace the poller to do something close to what `useSwr` is doing:

- Dedupe get threads request
- Ignore old request response if a new one has been triggered
- Schedule next polling when receiving a response or an event instead of fixed interval

Out of scope: 
- Trigger revalidation when browser go back online

**Comment by marcbouchenoire** [comment]
I'm not sure how much has changed since but `CommentsRoom` used to do exactly that? The poller was used in tandem with `AsyncCache` which handled deduplication/orchestration (it's a mini SWR), it was later copied over within `CommentsRoom` to be modified because adding mutations to `AsyncCache` in a generic way was too problematic
