### ISSUE TITLE
Auto link for Composer

### ISSUE THREAD

**Issue by GuillaumeSalles** [liveblocks/liveblocks#1077]
Create a Slate plugin that turns any links in the text into a link inline node. It should work when typing and pasting, breaking the link in the text should break the auto link as well.

Ideally, we should be able to build upon this with custom links (custom text) later on.

**Links:**
- [Slate inline nodes example](https://www.slatejs.org/examples/inlines)
- [A Slate linkify plugin](https://github.com/newsiberian/slate-plugins/blob/master/packages/slate-linkify/src/withLinkify.tsx)
- Possible inspiration: [Tiptap's auto link plugin](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-link/src/helpers/autolink.ts)
- Possible inspiration: [Lexical's auto link plugin](https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/LexicalAutoLinkPlugin.ts)

**Comment by nimeshnayaju** [comment]
### Description
Implement auto linking where URLs, email addresses, or other types of links are automatically detected and converted into clickable hyperlinks.

### Acceptance Criteria:

- [ ] The editor should detect URLs (starting with "http://" or "https://") as they are typed.
- [ ] When a URL pasted, it should be converted into a hyperlink.
- [ ] Breaking the link in the text should break the auto link as well.
- [ ] Users should be able to remove the hyperlink if needed. Popular other editors display a toolbar when a hyperlink is clicked on (see screenshots below). 

@GuillaumeSalles @marcbouchenoire I would love to hear your thoughts on this - If we choose to display a toolbar on hyperlink press:
1. Do we provide similar styling options as our other customizable components like the `Mention Suggestions` dropdown, `Mention` node. 
2. Do we want to also allow users to provide their own `Link` component (like the `Mention` component via `renderMention` prop) and their own toolbar component (like the `Mention Suggestions` dropdown via `renderMentionSuggestions` prop)?

<img width="432" alt="Screenshot 2023-08-31 at 9 42 29 PM" src="https://github.com/liveblocks/liveblocks/assets/35807215/9cf4c943-8b4c-4ba8-bc1e-a6f398aa4be9">

<img width="432" alt="Screenshot 2023-08-31 at 9 43 00 PM" src="https://github.com/liveblocks/liveblocks/assets/35807215/43abf7bc-41b8-43d5-854c-e5b59ad66084">

<img width="432" alt="Screenshot 2023-08-31 at 9 44 29 PM" src="https://github.com/liveblocks/liveblocks/assets/35807215/467e7b2b-df3e-4342-835a-3b9c1db1a024">

**Comment by adigau** [comment]
Here are my thoughts:
>  The editor should detect URLs (**starting with "http://" or "https://"**) as they are typed.
We shouldn't limit to URL starting with `http://`, a lot of people refer to websites without it, like facebook.com
See screenshot of GMAIL's behaviour 👇
![CleanShot 2023-09-01 at 14 19 22@2x](https://github.com/liveblocks/liveblocks/assets/10360044/080a3f59-7955-4a15-89cf-768cad3bd08b)

>  The editor should detect URLs (starting with "http://" or "https://") **as they are typed**.
I don't think that's mandatory as a V1 if it represents extra work, and might be complicated. The minimum needed is that when it's posted, the URL is clickable, like in GMAIL. The author doesn't absolutely need to see it transformed in realtime but would be better.
Analysis:
In Notion, it doesn't transform the URL for neither the author or the reader 🤷 But fun fact, they transform the URL in realtime ONLY for Notion URLs
![CleanShot 2023-09-01 at 14 23 08@2x](https://github.com/liveblocks/liveblocks/assets/10360044/0248e606-c8db-403f-903b-6493760d8585)
In FIgma, it transforms it in realtime as you type
![CleanShot 2023-09-01 at 14 25 07@2x](https://github.com/liveblocks/liveblocks/assets/10360044/81702c48-3484-4c8a-ba00-2ba2d6e7610e)
In Google Doc and Gmail, it doesn't transform as you type but transforms it for the reader
![CleanShot 2023-09-01 at 14 27 35@2x](https://github.com/liveblocks/liveblocks/assets/10360044/cc4294f3-1ebe-4af6-9967-95a86c5967f5)

**Comment by nimeshnayaju** [comment]
> 2️⃣ For comments it's always very simple and I'm not sure enabling a user to remove a link brings a lot of value.

Figma shows a floating popover when hovering or pressing on the link text while editing the comment. Once the comment is posted, clicking on the link takes user to the link. I personally find this UX quite good.

Notion does not display such popover when editing the comment but takes you directly to the link when you click on it - not a great UX from my perspective because while editing, as a user I'd expect to be able to edit the text.

What are your thoughts? @adigau What kind of UX are you more inclined towards?

<img width="346" alt="image" src="https://github.com/liveblocks/liveblocks/assets/35807215/082d3418-7f87-4966-aa48-98eeed2bc6ec">

**Comment by adigau** [comment]
@nimeshnayaju Thank you for that info, missed it. 
There are many options we can take. I honestly don’t believe a comment system needs to offer the ability to edit a link. But that’s something that could come up in the future as an important need.

Is that making the development faster to not implement it as part of this task?
If we don't implement it right now, is it going to slow us down later if we want to add it?

I'd go incrementally tbh so that we only invest on what we know is needed

**Comment by nimeshnayaju** [comment]
It would definitely make development easier if we do not implement the floating toolbar to edit link, and it won't slow us down in the future if we want to add it. Let's focus on that in future in that case. 

Now, with that all being said, what kind of UX do you think we should go for the parts we do want to implement? Do we want to do what Google Docs does? Treat a link as normal text while editing, but transform to a hyperlink in reader mode.

**Comment by adigau** [comment]
Decision made after discussion:
Since it’s not making us choose a path we’ll regret later or that will slow us down, we should go and implement a logic similar to Google Docs and Gmail:
- When you write a comment, a link is shown as plain text
- When the comment is read by someone, links are transformed and made clickable
Then, based on feedback, we could decide to make the experience better:
1. Transform a link while the author types it (like Figma does)
2. Add the possibility to edit a link and separate the URL from the label (like Figma does)
