### ISSUE TITLE
ID Token Read-only Permissions

### ISSUE THREAD

**Issue by gerardSlate** [liveblocks/liveblocks#1141]
**What is the improvement or update you wish to see?**

The Liveblocks read-only permissions example here: https://liveblocks.io/docs/rooms/permissions/id-token#permissions-levels-groups-accesses-example is a bit unclear. 

**Is there any context that might help us understand?**

When I attempted to just pass in ["room:read"] as the array, I kept getting an exception. This leads me to believe that there's some validation that requires that ["room:presence:write"] be present in the permissions array if the type is "READ". A clarification here would be really helpful.

**Comment by nvie** [comment]
Hey! The reason for this is that presence in the room is always writable (because presence is like an individual sandbox for each user, so it can always be changed). Specifying just `room:read`, permissions, might be ambiguous as it may falsely suggest that it would also set presence to read-only, which is not the case (and would also not make sense). That’s why we ask to be explicit and specify `room:presence:write` at the minimum, so that potential confusion is avoided. Hope this helps!
