### ISSUE TITLE
useThreads pagination

### ISSUE THREAD

**Issue by joelvarty** [liveblocks/liveblocks#1314]
Our solution uses the same rooms for long periods of time, so the number of threads in any given room can grow very large.

We would like to be able to page and filter the list of threads to maintain performance as we scale up.<br><br>Update: filtering has been implemented

**Comment by adigau** [comment]
Hello @joelvarty , I'm Adrien, Product Manager at Liveblocks!

Thank you for that feedback. We've split your feedback into two tasks:
1. Adding the ability to search for threads, so that you can only receive a subpart of what you need
2. Adding the ability to paginate the results

We believe that both will bring value, and splitting them allows us for brining value faster.

The first point should come rather soon, so I'll keep you posted. The second should follow soon after.

**Comment by CTNicholas** [comment]
Hey @joelvarty, just noticed this issue—we've enabled filtering threads by metadata, learn more in [our blog post](https://liveblocks.io/blog/liveblocks-1-9-comments-improvements-that-enable-ai-agents-chat-moderation-thread-filtering-and-more#thread-filtering).

We'll be looking to add more ways to filter threads next year.

**Comment by nvie** [comment]
Hey @joelvarty – just circling back here: we [published pagination support for our hooks](https://liveblocks.io/changelog#v2.9.0) two weeks ago, in case you missed the update! Hope this fixes your issues!

**Comment by joelvarty** [comment]
Yes I saw this! We will be incorporating this into our next update for sure! Thanks!!


Yours, Joel

Joel Varty
CTO, Agility CMS
416-613-9676
________________________________
