### ISSUE TITLE
Second presence is "blinking" on the multiplayer text editor with Tiptap and Yjs

### ISSUE THREAD

**Issue by henriquedevelops** [liveblocks/liveblocks#1347]
I'm building a multiplayer text editor with Liveblocks, Tiptap and Yjs

Everything seems to be working fine, except that the cursor/caret from the other presence is "blinking" when the text is focused by the primary user

![CPT2312120944-866x530](https://github.com/liveblocks/liveblocks/assets/47286998/67df6b36-00d3-4ff9-8cb9-79317d58a9cf)

This starts happening when I click on the text (focus on it)

**Comment by henriquedevelops** [comment]
Hey @stevenfabre could you please give me some help here?

I have no idea of what might be causing this problem

I commented out everything that is not directly related to the core functionality of the feature (like in [this example](https://liveblocks.io/examples/collaborative-text-editor/nextjs-yjs-tiptap)) but I still get this issue

**Comment by CTNicholas** [comment]
Hey @henriquedevelops, sorry we missed your issue! This is an unfixed Tiptap bug. Luckily it only happens when React's strict mode is enabled, which is only in development mode. In production, the issue doesn't occur.

I'm closing this because we have the same issue here: 
- https://github.com/liveblocks/liveblocks/issues/1161
