### ISSUE TITLE
history.batch() is not working at async callback function.

### ISSUE THREAD

**Issue by jiwon79** [liveblocks/liveblocks#1352]
**Describe the bug**
I use history.batch with async callback function. However it's result is not same with expected.

**To Reproduce**
**code**
```
const { room, leave } = client.enterRoom("my-room", {
    initialPresence: { x: 0 },
    initialStorage: { state: 0 },
  });
  const history = room.history;

  console.log("first", room.getPresence()); // expected : first 0
  await room.batch(async () => {
    console.log("startBatch");
    room.updatePresence({ x: 1 }, { addToHistory: true });
    console.log("second", room.getPresence()); // expected : second 1
    
    await new Promise((resolve) => setTimeout(() => resolve(""), 1000));

    room.updatePresence({ x: 2 }, { addToHistory: true });
    console.log("third", room.getPresence()); // expected : third 2
    console.log("endBatch");
  });
  history.undo();
  console.log("last", room.getPresence()); // expected : last 0
  ```

**Expected behavior**
I expected following console log result.
```
first 0
startBatch
second 1
third 2
endBatch
last 0
```
However real result it is.
```
fist 0
startBatch
second 1
third 2
endBatch
last 1
```

Is this behavior as intended? How do I use async function in room.batch?
If I use history.puase and history.resume at start and end of callback function, it work expected.

**Environment (please complete the following information):**

```
"dependencies": {
    "@liveblocks/client": "^1.8.2",
    "@liveblocks/react": "^1.8.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
},
```

**Comment by nvie** [comment]
Unfortunately, batching doesn't work with async functions. This is as-intended. The purpose of a batch is to group one or more sychronous (Presence or Storage) updates that will get combined into a single outgoing message to other clients. (Rather than each getting their own network message.) It will also cause multiple updates to end up as a single item in your undo/stack.

Also please note that, even if your batch function were synchronous, updating Presence twice like in your example, would not have an observable effect in other clients. To other clients, the first presence update `{ x: 1 }` will never be visible to other clients because immediately after the `{ x: 2 }`, part of the same batch, would "win".

So maybe the best way to structure this is to have an async function that will perform two separate batches with updates?

```ts
console.log("start updates");

// Batch 1: before the await
room.batch(() => {
  room.updatePresence({ x: 1 }, { addToHistory: true });
  // ... possibly more updates here
});
console.log("second", room.getPresence());
    
await new Promise((resolve) => setTimeout(() => resolve(""), 1000));

// Batch 2: after the await
room.batch(() => {
  room.updatePresence({ x: 2 }, { addToHistory: true });
  // ... possibly more updates here
});
console.log("third", room.getPresence());

console.log("end updates");
```

We could definitely make this clearer in our documentation, though, so thanks for pointing this out! 🙏

**Comment by jiwon79** [comment]
> the first presence update { x: 1 } will never be visible

Yes right and I want it. I wrote a simple example code(just delay 1 sec) to test async, but I will explain it in more detail with pseudo code.
```
// it's not work
// node is room Storage data
// room update function in updateNodeSize
room.batch(async () => {
  updateNodeSize(node, newParentSize)
  for (child at node.children) {
    const size = await getNodeSize(child)
    updateNodeSize(child, size * 2)
  }
} 
```
> So maybe the best way to structure this is to have an async function that will perform two separate batches with updates?

I use batch because I want to be able to cancel with a single redo. So I can't separate batches.

I think there seem to be two ways: 1. pre-async functions, 2. using history.pause. Which do you think is the better way to use history?

```
// 1. pre-async functions
const childrenSizes = await node.children.foreach(getNodeSize)
room.batch(() => {
  updateNodeSize(node, newParentSize)
  for (child, index at node.children) {
    updateNodeSize(child, childrenSizes[index])
  }
}
```

```
// 2. using history.pause & history.resume
history.pause()
updateNodeSize(node, newParentSize)
for (child at node.children) {
  const size = await getNodeSize(child)
  updateNodeSize(child, size * 2)
}
history.resume()
```

**Comment by nvie** [comment]
I'd recommend going with solution 2, because the undo stack is all local to the current client. You can keep history "paused" as long as you want, even asynchronously, and resume it later. All actions taken during the `.pause()` and `.resume()` call will then end up as a single item in your undo stack.

Additionally, it may be a good idea to wrap the code in a try/finally block:

```ts
history.pause();
try {
  // your code
} finally {
  history.resume();
}
```

**Comment by jiwon79** [comment]
I think your code is good solution in case. Thank you so much for your help so quickly.
