### ISSUE TITLE
EnsureJson is failing on a particular interface

### ISSUE THREAD

**Issue by oravecz** [liveblocks/liveblocks#1558]
**What is the improvement or update you wish to see?**

#166 introduced the concept of the `EnsureJson` helper method into the project.

I have a particular external interface that `EnsureJson` is not handling properly, so I'm not sure if this is a case where the documentation can be extended to indicate a new edge case, or whether it is a "bug" that can be resolved or has a workaround.

The Interface I am attempting to wrap with `EnsureJson` is `Attribute`. It's transitive dependencies look like this.

```ts
export const AttributeImpactEnum = {
    NONE: 'NONE',
    WARN: 'WARN',
    ERROR: 'ERROR'
} as const;

export type AttributeImpactEnum = typeof AttributeImpactEnum[keyof typeof AttributeImpactEnum];

export interface AttributeValue {
    v?: object;
}

export interface AttributeMatch {
    attrId: string;
    impact?: AttributeImpactEnum;
}

export interface AttributeDependency {
    anscestor?: Array<AttributeMatch>;
    peer?: Array<AttributeMatch>;
}

export interface Attribute {
    id: string;
    categoryId: string;
    value: AttributeValue;
    active: boolean;
    order: number;
    workbookId?: string;
    code?: string;
    dependency?: AttributeDependency;
}
```

Here is the use in code:

```ts
  const { room, leave } = client.enterRoom<Presence, Storage>(workbookId!, {
    initialPresence: { selectedItems: [] },
    initialStorage: {
      segments: new LiveList<EnsureJson<Segment>>(segments),
      attributes: new LiveList<EnsureJson<Attribute>>(attributes),
    },
  });
```

The `<EnsureJson<Attribute>>` is marked with an error condition. IntelliJ reports the error that `EnsureJson` is expected to resolve.

```
TS2344: Type
  {
     id: string;
   categoryId: string;
   value: {
     v?: object | undefined;
   };
   active: boolean;
   order: number;
   workbookId?: string | undefined;
   code?: string | undefined;
   dependency?: {
     anscestor?: {
       attrId: string;
       impact?: AttributeImpactEnum | undefined;
     }[] | undefined;
     peer?: { ...; }[] | undefined;
   } | undefined;
 }

does not satisfy the constraint Lson
Type '{ id: string; cate...efined; } | undefined; }' is not assignable to type 'JsonObject'.
  Property value is incompatible with index signature.
    Type { v?: object | undefined; } is not assignable to type Json | undefined
      Type { v?: object | undefined; } is not assignable to type JsonObject
        Property v is incompatible with index signature.
        Type object is not assignable to type Json | undefined```
```

** Some analysis**

Here is a [LiveLink](https://www.typescriptlang.org/play?module=1&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzjAnmApnAogOwM4CuU6AUnhDgDRwAywAbunXvAL5wBmUEIcA5AAEANg3QAjIRADGAazwB6KSPQ4YfANwAoTegAekWHCkUWcAIIwYUYGIIx0ASXABDKTFwFeAXkSa4-uAA5AHlArAAufhCwvko-AIB1MwAlQMi+JNTY+P8sZOTg5PS8guS+TXZnPCMTGC0dfWh4VAxzS2tbeycwV3ccTzgfFvQIDjarGztHFzcPEABtGXQUUeQ0EbGLCc7pntn+kABder0DeGBVdCgOV0wtjqmANWchAkwEHLh6AH5IiDEAFboNxaVjaU5NOAXezXW7jB72ACyzhgUgAFr4AnAUVYHAATSIsaw4ADmWixoD2MF+8MmXRmfU8oPBjUM0KuNykd3adPQABF0BgcHiVFIUJiAs58FyWNAaWYoFBnCgADz3XnI1FogB85ICGCu8sVyrVPJ2mvRuoqLLOUMusK5tJ2Ev8wAJcCJFzJnykKPQJOgKHxhImpL1-noLzekXVO2er3Q4exblEkTEEAgQnQUqT0BFUEiBzEVyTAHdoDJ0xAZPiaZ6wz6ICK66HvViRUKRTgxfKzVMBZ3RShmZpjPh4DiEeg8DG+-Z5odBnAF-UcOhS7RRMwYCrcIRiGQKKbtlNtdqABST3l4ACUQA)

The issue appears to be a problem with `EnsureJson` handling the following interface

```ts
export interface AttributeValue {
    v?: object;
}
```

**Does the docs page already exist? Please link to it.**

Ex. [https://liveblocks.io/docs/platform/troubleshooting#lson-constraint-and-interfaces)

**Comment by nvie** [comment]
Hi @oravecz, we [documented this issue here](https://liveblocks.io/docs/platform/troubleshooting#lson-constraint-and-interfaces), in case you're interested in the details.

Ultimately, the key issue that causes this type error is on line 12:

```ts
export interface AttributeValue {
    v?: object;  // 👈 An `object` isn't guaranteed to be JSON-serializable
}
```

In addition, from looking at your example, your best shot will be to use `type` instead of `interfaces`, if you are in control of those type definitions, and your application allows it.

- Change this `object` to `JsonObject`
- Change `interface` to `type` (which aren't "open" by default, and thus helps TypeScript understand that there won't be any non-JSON fields added to the type elsewhere)

Here is an [adjusted example](https://www.typescriptlang.org/play?module=1&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzgGWANwKaoM4wDRwBS2EAdgPIBGAVhgMbwC+cAZlBCHAOQACANugyU+EOgGtsAejoCMpGFwDcAKGUYAHpFhw6ZXHACCMGFGCUArjAwBJcAEMGAUVLnOAXkTK43uADlyvo4AXNz+gVx4Xj4A6gYASr4hXLEJEVHejnFx5HFJmdlxXMrMdtg6ejAqaprQ8DAAnmAYhsamFla2YA4wzq5wHg1NECwtJmaWNvZOLiAA2mIY9cNwgxjLRmPtk13TrgC6VRpadY3NG20TAGp2fObNHgjpcGgA-CHEZFS0DCqMqke1FanUYXKwAWTsMDoAAt+p4fHBISZrAATEK4UykADmKgRoB2MDeIPGHSmPRmv3+NW0q2JWwAIhgmqQUXI6PU4Y8EXZSNg6BhcNAiQYoFA7PUADznEkYCFQ6EAPlxPiaGCgwtF4qlrRlcphSuKVOOQKadImnKewDRcAxwGxyu8dEhGCx0HqqPRY3tTzQNzuIWlW2utwwDsRDEEIUoEAgfAwPLD0FZUBCM0oarDAHdoGJoxAxKiibbvQjdKyi16cU9WczWaR2cKdQymXI6+zKcpdLz4EjQQKA02JrM9nDh1VSBhMyhBDgYNrNhMFQAKXsy7AASmUQA) that works around this problem.

Hope this helps to explain and solves your issue. Feel free to re-open this issue if you have any further questions! 🙏

**Comment by oravecz** [comment]
Can we extend that Playground example a little bit more?

```ts
const attributes: (Attribute & Lson)[] = [];
const attribute = attributes[0] as unknown as (Attribute & LsonObject);

const list = new LiveList<Attribute & Lson>(attributes)
const item = new LiveObject<Attribute & LsonObject>(attribute);
list.push(item);
```

The last line doesn't seem to work with the types specified.

[Playground Link](https://www.typescriptlang.org/play?module=1&allowSyntheticDefaultImports=true&ssl=41&ssc=17&pln=36&pc=1#code/JYWwDg9gTgLgBAbzgGWANwKaoM4wDQroYDyARgFYYDG+cMAnmBithAHYENMvtmU1wAvnABmUCCDgByAAIAbIqTkQqAa2wB6KgoxsYUgNwAoIxgAekWHCrtccAIIwYUYKQCuMDAElwAQxoAomxukgC8iEZwUXAAcsQxAQBc0nEJUniR0QDq9gBKMclSOfnpmVEBubnEuYUVVblSRsK+2Na2MMamFtDwXMyOzq4e3n6BwWF0jBgQIg5OLu6ePmD+MEEhANqqGPQzk0x7AwvDy6vrIAC6neaW8MB6GFAi-v3zQ54Aar5ybswIZXA0AB+ZIQCjUDpNEw3Hpwe6eJ4vOaDRYYACyvhgVAAFhFonBMc4vAATZK4FxsADmxnxoBWNBByOOS1Ga3GxkE0O6Vnhj2eVFeKOGABEMEw2MTdFR6Hjor42NgBbhoIz7FAoL56AAeI7vdGYnEAPhp0SYj1V6s1OreqIxWOxxqhXVucIeiIFTL1sqiwFJcHJ92pAKomIwlOg9BJZMGVJNUTQ31+yV1qK+PwwcYJNCIyVIEAgcgw8sz0ElUGS41Ij0zAHdoKo8xBVCTGQHY8GIJLWzGg-jJeLJWxpaqbSKxbpB9KOSYbAr4ITmRhsMkABQp4ZwABkPDYAEoNhc4OED8ZZ3YF17whfUdgNgAGQ8tOBuNiqNgQGtsAmtNejzxbnc+AhXdOjPeAFDscI2AwGtCEwHAYGtIV-23ZBWDYQ0V2vYZsF3IwwLhTwJmg2DUEwICaCQxcALQ3hwRoTDsM8ECjAgmAADowDcbBsRXYAiJYoA)
