### ISSUE TITLE
Nested Rooms in React causing error

### ISSUE THREAD

**Issue by amcdnl** [liveblocks/liveblocks#1623]
## Bug Report

In my application, I have a 'home' room and then session rooms. Currently I have the application structured like:

```
<>
   <RoomProvider id="home">
        ... other stuff ...
       <Suspense fallback={<Loader />}>
         <RoomProvider={sessionId} initialStorage={{ input: new LiveObject({ value: '' }) }}>
             <Suspense fallback={<Loader />}>
               <MyComponent />
             </Suspense>
         </RoomProvider>
       </Suspense>
   </RoomProvider>
</>
```

and in `MyComponent` I would like to set the `input.value` as the user types like:

```
  const updateInput = useMutation(
    ({ storage }, value) => {
        storage.get("input").set("value", value);
    },
    []
  );
```

however, whenever I run the follow I get an error BEFORE `storage.get` is even hit when invoking `updateInput` that reads:

```
This mutation cannot be used until connected to the Liveblocks room
```

however, if I put the following code above the invocation of the `updateInput` function:

```
    const room = useRoom();
    const status = room.getStatus();
    if (status === 'connected') {
       updateInput(inputVal)
    }
```

the code still fails. I'm wondering if it has something to do with the nested rooms though this should totally work in react context.

## Additional Info

```
    "@liveblocks/client": "^1.12.0",
    "@liveblocks/react": "^1.12.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
```

**Comment by nvie** [comment]
Hi @amcdnl – thanks for opening a support ticket. The nesting of RoomProviders should not be an issue indeed—it's supported since [v1.5.0](https://github.com/liveblocks/liveblocks/releases/tag/v1.5.0).

The `useMutation` callback can only be called after the initial storage document has been loaded by your application. Waiting for `status === 'connected'` is not enough for this. That is only the WebSocket status. After the WebSocket is connected, the Storage loading phase begins. You can listen for the `storageStatus` status instead. If it's `synchronized` or `synchronizing`, it means it has been loaded. You can find the [relevant docs](https://liveblocks.io/docs/api-reference/liveblocks-client#Room.getStorageStatus) here.

Hope that helps to resolve it for you!

**Comment by nvie** [comment]
I realize that the error message may have put you on the wrong track. I'll get that fixed 👍

**Comment by amcdnl** [comment]
@nvie - Sadly, it never moves out of `not-connected`. Any clues why this might be?

**Comment by amcdnl** [comment]
@nvie - Here is the console output:

<img width="1538" alt="image" src="https://github.com/liveblocks/liveblocks/assets/227909/bd334fc1-c2d0-43ee-b734-8ee01ce36d22">

And here is my room structure - I have 1 main room called `home` and then a room for each `session` tab.

<img width="968" alt="image" src="https://github.com/liveblocks/liveblocks/assets/227909/3de2a11c-ea70-4ebd-9fbd-a80c09d26627">

**Comment by nvie** [comment]
@amcdnl Oh yeah, you will need to trigger a storage load explicitly, either by doing a `.getStorage()` call, or by using a hook like `useStorage`. I was under the assumption you were doing that already. Once storage starts loading, this should work for you. Please lmk if it is not!

**Comment by amcdnl** [comment]
Yup that works. Perhaps you should call that out in the docs. I'm going to close this now :D

**Comment by nizioleque** [comment]
Hi @nvie, what's the current state of support for multiple (nested) RoomProviders?

It seems like the support has been dropped since this issue was closed (now there is a single `RoomContext` that's used for all rooms). Is there a way to achieve this in the latest version?

**Comment by nvie** [comment]
This is indeed still a known limitation. Several calls to `createRoomContext()` where initially intended to be used mostly at the static/TypeScript level, letting you define different Presence, Storage, and UserMeta types for different room types, rather than creating runtime isolation.

I agree this isn't intuitive, and it's something we'd like to get fixed indeed.

Current vs desired behavior:

```tsx
const contextA = createRoomContext<TypesA>(client);
const contextB = createRoomContext<TypesB>(client);

<contextA.RoomProvider id="room-a">
  <contextB.RoomProvider id="room-b">
    {
      // 🐞 Current: contextA.useRoom().id currently returns room-b
      // ✅ Desired: contextA.useRoom().id should return room-a
    }
  </contextB.RoomProvider>
</contextA.RoomProvider>
```
