### ISSUE TITLE
Poison shapes can cause desync.

### ISSUE THREAD

**Issue by steveruizok** [liveblocks/liveblocks#34]
If a client creates a "big" shape (something with 2000+ characters worth of points) and then follow it up with another "big" shape, the second big shape sometimes does not sync. It also "blocks" any future syncs until this shape is deleted on the client that created it. Any idea of what's happening?

![Kapture 2021-11-22 at 12 38 32](https://user-images.githubusercontent.com/23072548/142863962-32bcd361-0264-4e34-9071-85e3d6380eb0.gif)

Some notes:
- This bug is found both on the 0.12.x and v0.13.0.beta.1.
- In an earlier implementation, I was storing the whole document state in a single `LiveObject`. After a refactor, I am storing shapes in a `LiveMap`. The bug happens in both cases.

**Comment by ofoucherot** [comment]
Hi Steve,

The issue was due to a limit in our key-value store.
Each LiveObject had a limit of 32 KiB (not including nested live objects).
In your case, a shape with 2000+ points, when each point contains three numbers, would reach the 32 KiB limit.

The limit was increased to 128 KiB, so your app should now handle shapes with more points. 

In the future, we will add a new "Live" type (for example LiveBlob) that will handle a much bigger object size.

**Comment by steveruizok** [comment]
Thanks for the update!
