### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by dynamichny** [liveblocks/liveblocks#38]
Cant find anything about this topic in documentation, but im wondering if the library supports React Native?
If not, do you plan to support this platform as well in future?

**Comment by GuillaumeSalles** [comment]
Hi @dynamichny,

To be completely transparent with you, we didn't try `@liveblocks/client` and `@livebocks/react` with react native, but my understanding is that it should work since we only depend on `fetch` and `WebSocket`. If it does not work for some reason,  we will make sure to fix the issues to make it work!

**Comment by GuillaumeSalles** [comment]
Based on @vinodsantharam feedback and some investigation, it's possible to use `@liveblocks/client` and `@liveblocks/react` with React native, but it requires some work. I'm reopening this issue to keep track of what could be improved to officially support React native.

Here are the necessary work around as of `v0.14.1`:

- use a polyfill for `atob` (used to parse jwt token)

```typescript
import {decode, encode} from 'base-64';

if (!global.btoa) {
  global.btoa = encode;
}

if (!global.atob) {
  global.atob = decode;
}
```

- Patch `window.addEventListener` to not crash on `window.addEventListener("online")`. 
```typescript
window.addEventListener = () => {};
```

To officially support it, we need to:
- Not crash on `window.addEventListener`. Give a clear error message when atob is not defined.
- Optional but it would great to use `@react-native-community/netinfo` to reconnect faster instead of waiting for the heartbeat.
- And of course, official documentation

**Comment by nandorojo** [comment]
for the online listener, maybe you could do what react-query does, and let people register their own listener.

**Comment by GuillaumeSalles** [comment]
We now have an official example: https://github.com/liveblocks/liveblocks/tree/main/examples/react-native-todo-list
