### ISSUE TITLE
Zustand V4

### ISSUE THREAD

**Issue by TheoBr** [liveblocks/liveblocks#422]
**Is your feature request related to a problem? Please describe.**

The Zustand package uses v3, it would be awesome if it supported v4

**Describe the solution you'd like**

The Zustand package supporting v4

**Additional context**

Mostly cutting this issue so I can send it to my community lol. Y'all cool with community contributions? 👀👀

**Comment by GuillaumeSalles** [comment]
Hi @TheoBr,

We plan to support zustand v4 in a future release. Either 0.18 or 0.19 because it will require breaking changes (zustand v3 and v4 middleware typings are completely different). 

We're cool with community contributions :) But this one might be quite challenging and require a good understanding of our internals. If you know someone up to the task, they can create a PR and we'll try to guide them the best we can.
