### ISSUE TITLE
[DOC_REQUEST] - Does leave automatically unsubscribe all handlers?

### ISSUE THREAD

**Issue by talksik** [liveblocks/liveblocks#598]
**What is the improvement or update you wish to see?**
Simply want to know more details of what different api endpoints do.

**Is there any context that might help us understand?**
I would like to know if it is important for us to clean up and what the point of the unsubscribe functions are.
  

Thank you so much!

**Comment by taylorpwhipp** [comment]
Hi Talksik, 

When leaving a room, unsubscribe is not called, however you are closing the connection to a room.  
Because of this, events that you were subscribed to should not continue to trigger storage updates.   Is that something which you have seen?

The main purpose of the subscribe function is similar to adding an event listener in javascript, and unsubscribe would correspond unbinding that listener-- so perhaps you only wanted to trigger subscribing to an event or unsubscribing to an event based off certain conditions or triggers.

Does that help clarify?

**Comment by talksik** [comment]
Got it thank you so much @taylorpwhipp!! Appreciate the detailed response.

I am now curious why my connections are inconsistent with turning off when a client's computer goes to sleep. Is there some delay in pinging clients to check connection?

**Comment by talksik** [comment]
Closing this as going to take the above comment to this thread : https://github.com/liveblocks/liveblocks/issues/679
