### ISSUE TITLE
[BUG] [Redux] CombineReducers breaks Liveblocks integration

### ISSUE THREAD

**Issue by ofoucherot** [liveblocks/liveblocks#606]
**Describe the bug**

When using the Liveblocks redux integration. An error message is logged in the console: `Unexpected key "liveblocks" found in previous state received by the reducer`.

Using `combineReducers` or having multiple nested slices breaks the Liveblocks redux integration.

Reproduced with:
- redux 4.2.0.
- liveblocks-redux 0.19.2.

**Comment by RickyC0626** [comment]
I'll look into this to see if it's still an ongoing problem.

**Comment by RickyC0626** [comment]
Since liveblocks enhancer has its own reducer that modifies state, I don't think it's possible to inject liveblocks state within a combined reducer (nor good practice). I tried creating a custom enhancer to see how I would eliminate the `Unexpected key error`, and came up with this:

```ts
configureStore({
  reducer: combineReducers({
    slice: slice.reducer,
    // Prevent unexpected key from being ignored
    custom: (state = null) => state,
  }),
  enhancers: [
    customEnhancer,
  ],
});
```

It seemed to work, until I tried doing the same with liveblocks enhancer. The collaboration still breaks, but it did prevent `Unexpected key error` from showing up for `liveblocks`. Although, the `Unexpected key error` will still show up for `shapes` because `presenceMapping` and `storageMapping` don't support nested state.

```ts
// Redux collaborative whiteboard example
configureStore({
  reducer: combineReducers({
    slice: slice.reducer,
    liveblocks: (state: LiveblocksState | null = null) => state,
  }),
  enhancers: [
    liveblocksEnhancer<State>({
      client,
      presenceMapping: { selectedShape: true },
      storageMapping: { shapes: true },
    }),
  ],
});
```

I wonder if the enhancer logic can be rewritten as a middleware function.

**Comment by nvie** [comment]
Hi @RickyC0626, thanks for digging in here!

From the [Redux docs](https://redux.js.org/usage/configuring-your-store#:~:text=Middleware%20adds%20extra%20functionality%20to%20the%20Redux%20dispatch%20function%3B%20enhancers%20add%20extra%20functionality%20to%20the%20Redux%20store.):
> _"a middleware adds extra functionality to Redux’s `dispatch` function, whereas an enhancer adds extra functionality to the Redux store"_

Going from that statement, I don't think we can (nor are supposed to) use a middleware here.

**Comment by RickyC0626** [comment]
> Going from that statement, I don't think we can (nor are supposed to) use a middleware here.

Ahh alright, that makes sense. I'll look into this from another angle.

**Comment by zeloxx** [comment]
wtf is this shit

**Comment by mikezaby** [comment]
I have the same problem and also agreed that there aren't real applications that using redux with a single reducer.

**Comment by zeloxx** [comment]
ill likely just use the client library and handle everything myself, tired of these weird quirks here and there.
