### ISSUE TITLE
Expose helper functions to serialize Lson structure into JSON for using liveblocks api endpoints

### ISSUE THREAD

**Issue by gcrespi** [liveblocks/liveblocks#625]
**Is your feature request related to a problem? Please describe.**

For some endpoints in liveblocks API such as [this](https://liveblocks.io/docs/api-reference/rest-api-endpoints#post-rooms-roomId-storage) you need to provide as the request body a serializable version of your Lson object. 

**Describe the solution you'd like**

It would be nice if `@liveblocks/client` would provide a function to transform Lson objects (LiveObject, LiveMap, LiveList, etc) in the needed structure, something like:

```
function convertLsonToJSON(value: Lson): JSONValue {
....
}
```

**Comment by nvie** [comment]
Hi @gcrespi, thanks for opening this issue. We agree this different data format is a bit cumbersome to deal with manually. We don't have a helper in the public API because it's we may soon offer a better API to populate storage, which will require less of this juggling. In the mean time, here is a code snippet you can use to convert an LSON tree to the needed data format: https://gist.github.com/nvie/09a34a3e3b219c442a418f033ce73e3a

**Comment by jrowny** [comment]
This has been completed
