### ISSUE TITLE
Single token authentication for multiple rooms

### ISSUE THREAD

**Issue by mk-marinov** [liveblocks/liveblocks#743]
**Is your feature request related to a problem? Please describe.**

Our domain model deals with two levels of user access on the same object: anonymous and registered. Anonymous users must be able to only see sections (subsets) of the collaborative data that is present for registered users. The data is split into different sections that are not presented on the same view, but are next to each other in our application (we want to be able to switch between them quickly).

As rooms are the granularity supported by liveblocks for access control, the obvious solution would be to split the data in two rooms (one accessible to anonymous & registered, the other to registered only).

However, working with two rooms presents some inconvenience in the current state. Every room must be entered with a specifically generated JWT. JWT generation takes ~1-1.5s at the moment, and entering the room takes roughly 0.5-1s. This results in minimum ~2.5s of navigation time (excluding other time spent in our application) which is slow for our use case. It also results in having to manage multiple JWTs to connect to liveblocks through the lifespan of our application frontend.

**Describe the solution you'd like**

The ability to request a single JWT which acts as an identity carrier and can be used to enter any room that computes some privilege based on identity data (user/group id) present in the JWT. For rooms that do not match any of the uid/gid in their access set, entering the room with the JWT will provide the default access (e.g. as if I were to enter the room with the public key at the moment).

This would allow us to use a single JWT per user session (similar to classic SSO), simplify JWT management, and not perform JWT generation on both our server and LB when switching between objects.

edit: Going into more implementation detail:
1. Expose a new API endpoint `/v2/authenticate` -- the name is an example. It issues multi-room JWTs. They have a different roomId marker compared to current JWTs -- either omit the field or a sentinel value.
2. The existing endpoint for per-room JWTs keep working the same way.
3. When connecting to a room, the authorization code looks at the JWT's roomId field, and...
3.1. If it's an "old style" per-room token, proceed with the current flow.
3.2. If it's a multi-room token, provide access to the room equivalent to the union of all privileges which match the token to the room by either user id or group id.

**Comment by nvie** [comment]
Someone on our team will take a look and get back to you with a response soon — thanks! 🙏

**Comment by styos** [comment]
Any updates on this? The slow per-room JWT generation is becoming rather limiting for our implementation.

**Comment by nvie** [comment]
I think this has fallen off our radar internally, my apologies. I'll throw it back in the group so we can discuss and we will respond here soon. Thanks for bringing this back to our attention, @styos! 🙏

**Comment by GuillaumeSalles** [comment]
Hi @mk-marinov and @styos,

Sorry for the delay; I planned to answer that before leaving for vacation, and it slipped through my radar...

Our authentication can feel pretty slow if you need to switch rooms often and it's definitely something we want to fix. (TBH, It’s one of my top personal pet peeves with Liveblocks with this [API flaw](https://github.com/liveblocks/liveblocks/issues/414))

I'm super impressed by what you’re proposing because it’s super close to what we have in mind :) 

#### Our plan

- Add a new authentication endpoint where `roomId` is optional. The generated token will contain what the user can do.
- If you're using `@liveblocks/node`, `roomId` option in `authorize` will become optional. If `roomId` is omitted, we will use the new authentication endpoint.
- As a user, it will be possible to use this token to connect to a room, but also call some REST APIs from the front-end. For example, getting the users inside a room without entering it ([docs](https://liveblocks.io/docs/api-reference/rest-api-endpoints#get-rooms-roomId-active-users.)).

We have already made some internal changes to implement this plan. Now, there are still some details that we’re trying to figure out to achieve this. 

- When we generate a token with the existing auth endpoint, a field `actor` is added to the token (can be seen if you decode the JWT). This is incremented for every token generated. `actor` is used by our storage solution. The client will get an `actor` only after connecting to the room with the new auth endpoint. Existing clients cannot read a token without an `actor`. We need to change our WebSocket protocol to achieve this and find a good way to explain how to migrate to the new auth endpoint.
- When should we **not** reuse a token? If the client receives a token with `userId: 'john'`, we will reuse this token to connect to multiple rooms and not call the `authEndpoint`. If John signs out, we shouldn't reuse this token for future connections. What kind of API should we expose to let the developer invalidate a token?
- Default token lifetime? Probably longer than what we have right now because the security is moved to the room level.

Any feedback about these details is greatly appreciated! It will definitely help us ship a better API. I’ll continue to update you as we progress on this.

**Comment by mk-marinov** [comment]
Thanks for the response! Adding my feedback to styos's:

> If John signs out, we shouldn't reuse this token for future connections. What kind of API should we expose to let the developer invalidate a token?

Hard question which depends on quite a few factors. Ultimately it ends up to the client application's architecture and requirements. Not all SSO systems support token revocation (e.g. SAML systems don't).

OAuth2 usually defines revocation for the longer-lived refresh token of an access/refresh token pair. But we only have access tokens here, and they are sufficient at least for our use case, as token re-issue is simple and serves the purpose of refresh. This brings us to token lifetime...

> Default token lifetime? Probably longer than what we have right now because the security is moved to the room level.

As the token still has bearer semantics (doesn't require key possession to use) and is used in browsers (can be compromised in many ways), long life is not a good idea from the security point of view.
But given that client applications can use a single token per user (rather than token per-room), the overall time spent in token management (issuing, keeping track, re-issuing) should be less.

If we assume that token lifetimes are short, which is IMO preferable in this case, revocation becomes less critical.
