### ISSUE TITLE
[FEATURE_REQUEST] Support non top level store keys on the `presenceMapping` option fo the 'liveblocksEnhancer' Redux enhancer 

### ISSUE THREAD

**Issue by DanielPFSeddi** [liveblocks/liveblocks#858]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the `presenceMapping` option on the liveblocksEnhancer from  `@liveblocks/redux`, but I only want to sync a sub-field of my store.

Imagine my store looks like this:
```
{
  scene: {
    selection: ['ItemA', 'ItemB'],
    children: [...]
  },
  ...
}
```

I only want to sync the `scene.selection` field, not the whole scene.

This is a very simple example, but in a real complex app you can have many different levels in your store, and only being able to sync top-level keys may not be the most convenient option. It would force you to sync some significant parts of your store that you don't need, just for syncing the small one you really want

**Describe the solution you'd like**

Support non-top-level keys in  the `presenceMapping` mapping, the interface could be like this:

`presenceMapping: { 'scene.selection': true }`

**Additional context**

I guess the related code would be around this line: [https://github.com/liveblocks/liveblocks/blob/main/packages/liveblocks-redux/src/index.ts#L394](https://github.com/liveblocks/liveblocks/blob/main/packages/liveblocks-redux/src/index.ts#L394)

**Comment by nvie** [comment]
Hi Daniel, unfortunately electing specifically which parts of deep structures to sync with Liveblocks is currently not possible. The `presenceMapping` is a pretty simplistic configuration, which only supports top-level keys, and opting-in is all or nothing.

Possible ways around that are currently:

1. Structure your store so that the parts you want to sync with Liveblocks live in your store under a top-level key (e.g. use something like `sceneSelection: true`), and somehow reassemble the `scene` as a derived property whenever the `selection` (or the rest of the `scene`) changes. Using a custom Redux selector this is often not that complicated.
2. Use the lower-level `@liveblocks/client` package instead of the `@liveblocks/redux` integration to more directly control your presence and storage shapes. This may not be necessary in your case.

Hope that helps — please let us know if you have any further questions.

**Comment by DanielPFSeddi** [comment]
Hi Vincent, thanks for your advice.

We've finally solved it using the `@liveblocks/redux` and `presenceMapping`, together with a redux middleware that syncs the specific parts of our store we want to share with a single top-level key object of our store. 

That way we can keep our store as it is, and benefit from the simple yet powerful integration `presenceMapping` provides.

Thanks!
